@startuml
class Application{
    +main()
        launch()
}

class TodoList{
    +addItem()
    +deleteItem()
    +clearItems()
}

class TodoListItem{
    -description
    -dueDate
    -completedStatus
    +setDescription()
    +getDescription()
    +setDueDate()
    +getDueDate()
    +getStatus()
    +setStatus(boolean Status)
    +editDescription()
}

class FilterItems{
    filterItems();
}

class Save{
    +setFileName()
    +setFileLocation()
    +writeList()
}

class Load{
    +loadFIle()
    +getLoadedFile();
}

Application <|-- Load
Application <|-- TodoListItem
Application <|-- TodoList
Application <|-- FilterItems
Application <|-- Save

@enduml